version: "3"

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3333:3000"
  api:
    build:
      context: ./api
    restart: always
    ports:
      - "5555:5000"
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - "8887:8080"
