version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3333:3000"
  api:
    build:
      context: ./api
    ports:
      - "5555:5000"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
  adminer:
    image: adminer
    ports:
      - "8887:8080"
